### ISSUE TITLE
meet a bug  run the inderence.

### ISSUE THREAD

**Issue by yxandam** [cyhuang-tw/AdaIN-VC#8]
run log as below.
\Anaconda3\lib\site-packages\torchaudio\extension\extension.py:13: UserWarning: torchaudio C++ extension is not available.
  warnings.warn('torchaudio C++ extension is not available.')
Traceback (most recent call last):
  File "E:/vioce_conversion/AdaIN-VC-master/inference.py", line 49, in <module>
    main(**vars(parser.parse_args()))
  File "E:/vioce_conversion/AdaIN-VC-master/inference.py", line 30, in main
    src = wav2mel(src, src_sr)[None, :].to(device)
  File "C:\Users\yxandam\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\vioce_conversion\AdaIN-VC-master\data\wav2mel.py", line 55, in forward
    wav_tensor = self.sox_effects(wav_tensor, sample_rate)
  File "C:\Users\yxandam\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\vioce_conversion\AdaIN-VC-master\data\wav2mel.py", line 89, in forward
    wav_tensor, _ = apply_effects_tensor(wav_tensor, sample_rate, self.effects)
  File "C:\Users\yxandam\Anaconda3\lib\site-packages\torchaudio\_internal\module_utils.py", line 35, in wrapped
    raise RuntimeError(f'{func.__module__}.{func.__name__} requires {req}')
RuntimeError: torchaudio.sox_effects.sox_effects.apply_effects_tensor requires module: torchaudio._torchaudio

PS C:\Users\yx> pip install torchaudio
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: torchaudio in c:\users\yx\anaconda3\lib\site-packages (0.8.1)
Requirement already satisfied: torch==1.8.1 in c:\users\yx\anaconda3\lib\site-packages (from torchaudio) (1.8.1+cu101)
Requirement already satisfied: dataclasses in c:\users\yx\anaconda3\lib\site-packages (from torch==1.8.1->torchaudio) (0.8)
Requirement already satisfied: numpy in c:\users\yx\anaconda3\lib\site-packages (from torch==1.8.1->torchaudio) (1.19.5)
Requirement already satisfied: typing-extensions in c:\users\yx\anaconda3\lib\site-packages (from torch==1.8.1->torchaudio) (3.7.4.3)
PS C:\Users\yx>

**Comment by cyhuang-tw** [comment]
Hi,

I think this problem is related to torchaudio but not the inference code.
Maybe you have to build the package on your own (with SoX) instead of using pip, and you can follow the steps described in [the official repository](https://github.com/pytorch/audio#from-source).

**Comment by yxandam** [comment]
Your project is very interesting. OK, I'll test it. Thank you very much for your reply.
